import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    //AGUA
{	
  name:'AGUA BONAFONT 1.5 LT (x 12)',
  category:'AGUA',
  image:'/images/p3.jpg',
  price:88,
  countInStock:483,
  brand:'AGUA',
  rating:5,
  numReviews:17,
  description:'high quality product',
},


{	
name:'AGUA BONAFONT 1LT  (x 12)',
category:'AGUA',
image:'/images/p3.jpg	 ',
price:69,
countInStock:956,
brand:'AGUA',
rating:5,
numReviews:17,
description:'high quality product',
},


{	
name:'AGUA BONAFONT 600ML (x 24)',
category:'AGUA',image:'/images/p3.jpg',
price:	109,
countInStock:1078,brand:'AGUA',
rating:5,
numReviews:17,
description:'high quality product',
},

{	name:'AGUA CRYSPURA 1.5ML  (x 12)',
category:'AGUA',
image:'/images/p3.jpg',price:75,
countInStock:1285,
brand:'AGUA	',
rating:5,
numReviews:17,
description:'high quality product',
},

{	
  name:'AGUA CRYSPURA 1LT (x 12)',
  category:'AGUA',
  image:'/images/p3.jpg',
  price:75,
  countInStock:877,
  brand:'AGUA',
  rating:5,
  numReviews:17,
  description:'high quality product',
},

{	
  name:'AGUA CRYSPURA 500ML  (x 24)',
  category:'AGUA',
  image:'/images/p3.jpg',
  price:75,
  countInStock:333,
  brand:'AGUA',
  rating:5,
  numReviews:17,
  description:'high quality product',
},
{	
  name:'AGUA NESTLE 1 LT  (x 12)',
  category:'AGUA',
  image:'/images/p3.jpg',
  price:70,
  countInStock:33,
  brand:'AGUA',
  rating:5,
  numReviews:17,
  description:'high quality product',
},

{
  name:'AGUA NESTLE 1.5 LT  (x 12)',
  category:'AGUA',
  image:'/images/p3.jpg',
  price:49,
  countInStock:0,
  brand:'AGUA',
  rating:5,
  numReviews:17,
  description:'high quality product',
},
{name:'AGUA NIAGARA  1 LT  (x 15)',
category:'AGUA',
image:'/images/p3.jpg	',
price:67,
countInStock:65,
brand:'AGUA',
rating:5,
numReviews:17,
description:'high quality product',
},

{	
  name:'BRANDY  AZTECA DE ORO  200 ML',
  category:'VINOS',
  image:'/images/p3.jpg',
  price:48,
  countInStock:87,
  brand:'VINOS',
  rating:5,
  numReviews:17,
  description:'high quality product',
},

//BEBIDAS PREPARADAS
{	name:'RED BULL 250ML (x 24)',
category:'BEBIDAS ENERGETICAS',
image:'/images/p3.jpg',
price:710,
countInStock:844,
brand:'ENERGETICAS',
rating:5,
numReviews:17
,description:'high quality product',
},

{	name:'VITALOE  320 ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:245,countInStock:109,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MONSTER TAURINE DRINK 473ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:599,countInStock:202,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA BOOST ACTIVE ENERGY 235ML (x 24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:380,countInStock:1,brand:'ENERGETICAS',rating:5,numReviews:17,description:'	high quality product',},
{	name:'BEBIDA VIVE 100 300ML VERDE (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:198,countInStock:121,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA VOLT LATON C/15  473ML (x15)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:175,countInStock:163,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA VIVE 100 #500ML AZUL (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:245,countInStock:9,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA VIVE 100 #500ML VERDE (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:245,countInStock:135,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA AMPER  473 ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:325,countInStock:323,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA ACAI MOTION 355 ML (x12)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:169,countInStock:81,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'H2O POWER VERDE 355 ML (x12)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:180,countInStock:70,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'H2O POWER CITRUS 355 ML (x 12)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:180	 ,countInStock:68	 ,brand:'ENERGETICAS	 ',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA MEDUSA ULTLAVIOLETA UVA 2LT (x 6)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:457,countInStock:28,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA MEDUSA DURAZNO 2LT (x 6)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:457,countInStock:28,brand:'	ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA HELIX HARD SELTZER TORONJA 355 ML(x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:478,countInStock:48,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA HELIX HARD SELTEZER MANGO  355 ML(x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:478,countInStock:47,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA HELIX HARD SELTZER LIMON  355 ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:478,countInStock:49,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA HELIX HARD SELTZER FRUTOS ROJOS 355 ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:478,countInStock:42,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'VITALOE  500 ML (x24)',category:'BEBIDAS ENERGETICAS',image:'/images/p3.jpg',price:270,countInStock:15,brand:'ENERGETICAS',rating:5,numReviews:17,description:'high quality product',},

//BEBIDAS PREPARADAS 
{	name:'CARIBE COOLER TINTO 300ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:368,countInStock:647,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX PALOMA LATA 355 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:346,countInStock:2573,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX VAMPIRO LATA 355ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:346,countInStock:821,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SKYY BLUE CITRUS  275 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:460,countInStock:208,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'RANCHO MIX 355ML C/24 (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:210,countInStock:18,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JACK DANIELS LATA MINERAL 355ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:505,countInStock:15,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GRAND DOUGLAS LATA 473ML C/24 (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:445,countInStock:40,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX MINERAL LIMON 350ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:346,countInStock:1,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX LATON VAMPIRO 473ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:454,countInStock:771,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX #LATON# 473ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:454,countInStock:882,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:	17,description:'high quality product',},
{	name:'BEBIDA CAMPO MIX 355ML C/24PZAS (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:267,countInStock:988,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'NEW MIX MINERAL NARANJA 350ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:346,countInStock:1	,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JACK DANIEL´S LATA COLA  355 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:505,countInStock:3,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JACK DANIEL`S LATA HONEY  355 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:505,countInStock:0,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CARIBE COOLER LIMON 300 ML(x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:368,countInStock:184,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CARIBE #ULTRA# DURAZNO 300 ML (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:199,countInStock:33,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'AGAVE MIX TAMARINDO 355 ML (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:210,countInStock:221,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'AGAVE MIX MANGO 355 (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:210,countInStock:28,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CARIBE COOLER MANDARINA 300ML(x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:368,countInStock:199,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA PERLA DORADA LATON 473  473 ML (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:315,countInStock:20,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BEBIDA PERLA PURPURA LATON 473ML 473 ML (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:315,countInStock:20,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SKYY BLUE ON THE BEACH  275 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:460,countInStock:18,brand:'BEBIDAS PREPARADAS',rating:5	,numReviews:17,description:'high quality product',},
{	name:'SKYY BLUE COSMO 275 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:460,countInStock:2,brand:'BEBIDAS PREPARADAS',rating:	5,numReviews:17,description:'high quality product',},
{	name:'SKYY BLUE APPLETINI 275 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:460,countInStock:9,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SKYY BLUE SUNSET 275 ML (x 24)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:460,countInStock:1,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CARIBE HARD SELTZER LIMA-LIMON 300 ML (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:218,countInStock:31,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CARIBE HARD SELTZER JAMAICA 300 MG (x 12)',category:'BEBIDAS PREPARADAS',image:'/images/p3.jpg',price:218,countInStock:32,brand:'BEBIDAS PREPARADAS',rating:5,numReviews:17,description:'high quality product',},
//CERVEZA
{	name:'CERVEZA MODELO 355ML(x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:298,countInStock:18951,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA MICHELADA *LATON*(x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:408,countInStock:290,brand:'CERVEZA',rating:5,numReviews:12,description:'high quality product',},
{	name:'CERVEZA PACIFICO MEDIA C/24. (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:320,countInStock:384,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CAGUAMA FAMILIAR 1LT (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:290,countInStock:6469,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA 1/2 CLARA (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:249,countInStock:4895,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA 1/2 OSCURA (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:260,countInStock:3600,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA OLDMILWAUKEE LATA 473ML C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:380,countInStock:0,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA DE BARRIL 335ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:203,countInStock:3191,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA LATON 473ML C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:330,countInStock:6932,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA MODELO #ESP CLARA C/12 (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:180,countInStock:2012,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA NEGRA MODELO #ESP C/12 (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:180,countInStock:1616,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA EXTRA  #LATA# 355ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:285,countInStock:727,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA ESTRELLA MEDIANA C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:275,countInStock:219,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA MEDIA C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:249,countInStock:448,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA 1/4 CLARA (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:155,countInStock:4846,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA 1/4 OSCURA (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:160,countInStock:5042,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA ESTRELLA *LATON 473ML(x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:315,countInStock:26339,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA #LIGHT# 355ML RET (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:310,countInStock:229,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERV. CORONA MEGA 1.200  LT (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:345,countInStock:11873,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA LIGHT 6 PACK (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:248,countInStock:31811,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA MEGA 1200ML (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:340,countInStock:1578,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA *LATON* EXTRA 473ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:20,countInStock:5833,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA MODELO #LATON# 473ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:335,countInStock:3072,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA STELLA ARTOS 330 C/24PZAS (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:390,countInStock:172,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA 473ML #LIGHT# LATON (x 24',category:'CERVEZA',image:'/images/p3.jpg',price:330,countInStock:3646,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA ##1.05 LT LIGHT C/12 (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:355,countInStock:204,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA ESTRELLA 1/4 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:185,countInStock:536,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'MICHELOB ULTRA LIGHT LATA C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:310,countInStock:1438,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'MICHELOB ULTRA LIGHT VIDRIO C/24 (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:305,countInStock:1370,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA "CERO" 355ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:330,countInStock:1,brand:'CERVEZA',rating:5,numReviews:17,description:'igh quality product',},
{	name:'CERVEZA MINERVA CAJOTA FELIZ 355 ML (x 12)',category:'CERVEZA',image:'/images/p3.jpg',price:350,countInStock:1,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA FORTUNA CAÑITA LAGER 355 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:740,countInStock:13,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA FORTUNA IPPOLITA 355 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:740,countInStock:4,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA FORTUNA CAÑITA LIGHT 355 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:740,countInStock:14,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA CHAMOY 473 ML (x 24)	',category:'CERVEZA',image:'/images/p3.jpg',price:460,countInStock:0,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA #CHINGONES 473 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:340,countInStock:1,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA BARRIL 335 ML #RETORNABLE# (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:240,countInStock:129,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA VICTORIA 710 ML (x 12)	',category:'CERVEZA',image:'/images/p3.jpg',price:	295,countInStock:118,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA CORONA EXTRA 1.8 #LATA# 355ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:390,countInStock:1,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA SOL CLAMATO 473 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:340,countInStock:88,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA TECATE LIGTH 473 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:255,countInStock:5,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},
{	name:'CERVEZA TECATE 473 ML (x 24)',category:'CERVEZA',image:'/images/p3.jpg',price:255,countInStock:52,brand:'CERVEZA',rating:5,numReviews:17,description:'high quality product',},

//CIGARROS
{	name:'CHESTERFIELD ORIGINAL 15`s (x 8)',category:'CIGARROS',image:'/images/p3.jpg',price:290,countInStock:168,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL VERDE ALASKA (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:551,countInStock:1222,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL BLANCO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:512,countInStock:245,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL ROJO  (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:512,countInStock:168,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO BLANCO #14´S (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:456,countInStock:51,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CHESTERFIELD REMIX PURPURA(x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:465,countInStock:6,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO ROJOS (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:1457,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BENSON & HEDGES DORADOS (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:108,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BENSON & HEDGES MENTOLADOS (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:70,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BENSON DORADO #LIGHT (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:30,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO BLANCO #100 (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:45,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO BLANCO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:432,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'DELICADOS OVALADOS C/18 SIN FILTRO (x 12)',category:'CIGARROS',image:'/images/p3.jpg',price:592,countInStock:26,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO ROJO #100 (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:110,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BENSON MENTOLADO #LIGHT (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:26,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MARLBORO ICE EXPRESS (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:42,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO ROJO #14 (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:456,countInStock:129,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL EXACTO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:341,countInStock:820,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS LUCKY STRIKE ROJOS (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:551,countInStock:219,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS LUCKY STRIKE AMARILLO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:569,countInStock:133,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MARLBORO DOUBLE FUSION VELVET (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:71,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MARLBORO RUBYFRESH MENT 100 (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:614,countInStock:166,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MONTANA 15 (x 12)',category:'CIGARROS',image:'/images/p3.jpg',price:437,countInStock:846,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS FAROS SIN FILTRO 18´S (x 12)',category:'CIGARROS',image:'/images/p3.jpg',price:581,countInStock:0,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CHESTERFIEL ORIGINAL 25´S (x 8)',category:'CIGARROS',image:'/images/p3.jpg',price:432,countInStock:184,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL PEPINO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:551,countInStock:540,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ENCENDEDORES BIC C/15 PZ',category:'CIGARROS',image:'/images/p3.jpg',price:238,countInStock:1575,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MONTANA SHOTS 25 (x 8)',category:'CIGARROS',image:'/images/p3.jpg',price:433,countInStock:536,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS GARAÑON (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:215,countInStock:428,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS L&M RODEO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:341,countInStock:105,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CHESTERFIELD REMIX FRESH-MENT(x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:445,countInStock:16,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'BENSON VIOLET  MENTHOL 100 (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:512,countInStock:47,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MARLBORO FUSION SUMMER (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:496,countInStock:115,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS MARLBORO ROJO REPOSADO (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:496,countInStock:43,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL NEW YORK (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:493,countInStock:252,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CIGARROS PALL MALL CALIFORNIA (x 10)',category:'CIGARROS',image:'/images/p3.jpg',price:551,countInStock:198,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CHESTERFIELD REMIX PASSION (x 10)	',category:'CIGARROS',image:'/images/p3.jpg',price:445,countInStock:13,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MARLBORO FUSION GARDEN (x 10)	',category:'CIGARROS',image:'/images/p3.jpg',price:496,countInStock:40,brand:'CIGARROS',rating:5,numReviews:17,description:'high quality product',},


//JUGOS
{	name:'JUMEX #LATA# MANZANA 355ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:185,countInStock:39,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE SPORT 600ML LIMA (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:368,countInStock:82,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE 500ML LIMA (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:325,countInStock:177,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE 500ML NARANJA (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:325,countInStock:267,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE SPORT NARANJA 600ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:368,countInStock:134,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX #LATA# DURAZNO 355ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:185,countInStock:103,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX MINIBRINK DURAZNO 250ML (x 40)',category:'JUGOS',image:'	images/p3.jpg',price:225,countInStock:408,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX MINIBRIK MANZANA 250ML (x 40)',category:'JUGOS',image:'/images/p3.jpg',price:225,countInStock:208,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CLAMATO 296ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:381,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX BOTELLIN DURAZNO #250  (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:149,countInStock:70,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'MALTEADA HERSHEYS CHOCOLATE 236ML (x 27)',category:'JUGOS',image:'/images/p3.jpg',price:180,countInStock:774,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CLAMATO 473ML(x 12)',category:'JUGOS',image:'/images/p3.jpg',price:195,countInStock:289,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CLAMATO DE 2 LITROS',category:'JUGOS',image:'/images/p3.jpg',price:46,countInStock:1177,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'CLAMATO 946ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:350,countInStock:145,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE T/R NARANJA 1LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:240,countInStock:194,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'GATORADE T/R LIMA 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:240,countInStock:204,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX BOTELLA DURAZNO 450ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:	215,countInStock:790,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX LATA BOTELLA DURAZNO 500ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:135,countInStock:66,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX LATA BOTELLA MANZANA 500ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:135,countInStock:73,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX LATA BOTELLA MANGO 500ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:135,countInStock:102,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX LATA BOTELLA PIÑA 500ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:135,countInStock:37,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA VERDE 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:370,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA KIWI-FRESA 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:140,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA SANDIA 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:134,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA LIMON 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:493,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA MANGO 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:222,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'ARIZONA COMBINADO 695ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:270,countInStock:443,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK NARANJA 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:33,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK MANZANA 1LT(x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:52,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK DURAZNO 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:42,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK PIÑA 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:112,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK MANGO 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:56,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX TETRAPACK UVA 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:204,countInStock:72,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT COCO 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:432,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT FRESA 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:819,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT TE VERDE 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:21,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT PIÑA 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:539,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT FRESA-KIWI 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:668,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT JAMAICA 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:384,brand:'jUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT MORA 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:654,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUMEX UNICOFRESCO ARANDANO 1 LT (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:234,countInStock:75,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'SUERO ELECTROLIT HORCHATA 625ML (x 12)',category:'JUGOS',image:'/images/p3.jpg',price:188,countInStock:460,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE NECTAR MANGO 413 ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:229,countInStock:14,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE NECTAR DE DURAZNO 413 ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:229,countInStock:14,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE NECTAR DE MANZANA 413 ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:229,countInStock:14,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE MANZANA 413 ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:229,countInStock:14,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE NECTAR DE GUAYABA 413 ML (x 24)',category:'JUGOS',image:'/images/p3.jpg',price:229,countInStock:14,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},
{	name:'JUGO DEL VALLE MANZANA C/ARANDANO 1 LT (x 6)',category:'JUGOS',image:'/images/p3.jpg',price:120,countInStock:54,brand:'JUGOS',rating:5,numReviews:17,description:'high quality product',},


// REFRESCOS
{name:'COCA COLA LATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:273,countInStock:249,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCA COLA TAPARROSCA 500ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:325,countInStock:1611,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCA COLA LIGHT 1L(x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:210,countInStock:18,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL NATURAL 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:225,countInStock:436,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL FRESA 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:245,countInStock:45,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSI 600ML /(x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:121,countInStock:243,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVEN 600ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:121,countInStock:251,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MIRINDA 600ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:121,countInStock:81,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MANZANITA SOL 600ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:121,countInStock:107,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL MANDARINA 600ML(x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:245,countInStock:50,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'TONICOL 355ML PLASTICO (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:191,countInStock:370,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSILATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:207,countInStock:115,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVENLATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:207,countInStock:54,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MIRINDA LATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:207,countInStock:46,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MANZANITA SOL LATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:207,countInStock:62,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SQUIRT 600MLC/24(x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:208,countInStock:236,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'AGUAMINERAL TOPOCHICO 600ML(x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:158,countInStock:85,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL NATURAL 2L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:142,countInStock:1221,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCACOLA LIGHT LATA 355ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:273,countInStock:76,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCACOLA LIGHT TAPARROSCA 500ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:325,countInStock:139,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCACOLA LIGHT 2L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:196,countInStock:40,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'REFRESCO RED COLA 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:200,countInStock:53,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL FRESA 2LT (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:128,countInStock:21,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL MANDARINA 2LT (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:128,countInStock:39,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCA COLA 2.5 (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:245,countInStock:880,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSI 2.5L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:192,countInStock:126,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVEN 2.5LT (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:192,countInStock:86,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MIRINDA 2.5L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:192,countInStock:47,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MANZANITA SOL 2.5L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:192,countInStock:45,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'TONICOL 600ML C(x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:283,countInStock:120,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SQUIRT 2LT (x9)',category:'REFRESCOS',image:'/images/p3.jpg',price:165,countInStock:1603,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SIDRAL 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:200,countInStock:80,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SIDRAL 2LT (x9)',category:'REFRESCOS',image:'/images/p3.jpg',price:150,countInStock:189,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'REFRESCO RED COLA2 LT(x9)',category:'REFRESCOS',image:'/images/p3.jpg',price:150,countInStock:84,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'REFRESCO RED COLA 1LT(x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:120,countInStock:283,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCA 500 RETORNABLE VIDRIO (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:210,countInStock:686,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSI 3LT (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:216,countInStock:37,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVEN 3LT (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:216,countInStock:40,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVEN 1.5ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:171,countInStock:122,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSI 400ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:79,countInStock:103,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SEVEN 400ML  (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:79,countInStock:112,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MIRINDA 400ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:79,countInStock:113,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'MANZANITA SOL 400ML (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:79,countInStock:97,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL NARANJADA 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:245,countInStock:15,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEÑAFIEL LIMONADA 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:245,countInStock:66,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'COCA COLA 1.250L (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:210,countInStock:160,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SANGRIA SENORIAL 600ML (x24)',category:'REFRESCOS',image:'/images/p3.jpg',price:232,countInStock:315,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'SANGRIA SENORIAL 2L (x8)',category:'REFRESCOS',image:'/images/p3.jpg',price:162,countInStock:1,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'PEPSI 1.5 (x12)',category:'REFRESCOS',image:'/images/p3.jpg',price:171,countInStock:114,brand:'REFRESCOS',rating:5,numReviews:17,description:'highqualityproduct',},

//VINOS
{name:'BRANDY TORRES 10 750ML',category:'VINOS',image:'/images/p3.jpg',price:252,countInStock:868,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY DON PEDRO 1LT',category:'VINOS',image:'/images/p3.jpg',price:160,countInStock:568,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY PRESIDENTE 200ML',category:'VINOS',image:'/images/p3.jpg',price:37,countInStock:444,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY DON PEDRO 200ML',category:'VINOS',image:'/images/p3.jpg',price:40,countInStock:1682,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY DON PEDRO RESERVA 700ML',category:'VINOS',image:'/images/p3.jpg',price:135,countInStock:391,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY AZTECA DE ORO 700ML',category:'VINOS',image:'/images/p3.jpg',price:150,countInStock:364,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY TORRES 5 750ML',category:'VINOS',image:'/images/p3.jpg',price:190,countInStock:863,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY PRESIDENTE 940ML',category:'VINOS',image:'/images/p3.jpg',price:135,countInStock:553,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY PRESIDENTE 500ML',category:'VINOS',image:'/images/p3.jpg',price:85,countInStock:280,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY PRESIDENTE 700ML',category:'VINOS',image:'/images/p3.jpg',price:120,countInStock:476,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY AÑEJOLOS REYES 940ML',category:'VINOS',image:'/images/p3.jpg',price:79,countInStock:816,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY AÑEJOLOS REYES 700ML',category:'VINOS',image:'/images/p3.jpg',price:59,countInStock:73,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY DON PEDRO 500ML',category:'VINOS',image:'/images/p3.jpg',price:95,countInStock:670,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY DON PEDRO 750ML',category:'VINOS',image:'/images/p3.jpg',price:275,countInStock:251,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY PRESIDENTE 750ML',category:'VINOS',image:'/images/p3.jpg',price:217,countInStock:190,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY TORRES 15 700 ML',category:'VINOS',image:'/images/p3.jpg',price:490,countInStock:173,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY TORRES 20 EDICION ESPECIAL 700ML',category:'VINOS',image:'/images/p3.jpg',price:885,countInStock:7,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY AÑEJO LOS REYES 250ML',category:'VINOS',image:'/images/p3.jpg',price:29,countInStock:812,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY CONDE HERRERA VSOP 700ML',category:'VINOS',image:'/images/p3.jpg',price:269,countInStock:10,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},
{name:'BRANDY AZTECA DE ORO 200ML',category:'VINOS',image:'/images/p3.jpg',price:48,countInStock:87,brand:'VINOS',rating:5,numReviews:17,description:'highqualityproduct',},


  ],


};
export default data;
